# Generated by Django 4.1.6 on 2023-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='username',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
